// frontend/svelte-app/src/lib/pages/Tasks.svelte
<script lang="ts">
  import {useMutation, useQuery, useQueryClient} from '@sveltestack/svelte-query';
  import axios from 'axios';
  import MutateTaskModal from "../components/MutateTaskModal.svelte";
  import type {Task} from "../models";
  import TaskCard from "../components/TaskCard.svelte";

  const taskTabs = {
    all: 'All',
    upcoming: 'Upcoming',
    done: 'Done'
  }

  let currentTab = taskTabs.all

  let modalState = {
    show: false,
    task: null,
  }

  const filterTasks = (tasks: Task[], currentTab: string) => {
    switch (currentTab) {
      case taskTabs.all:
        return tasks
      case taskTabs.upcoming:
        return tasks.filter(x => x.time && new Date() < new Date(x.time))
      case taskTabs.done:
        return tasks.filter(x => x.status === 'done')
    }
  }

  const queryClient = useQueryClient()

  const queryResult = useQuery('tasks', () =>
    axios.get('http://localhost:4000/api/tasks')
  );

  const deleteTaskMutation = useMutation((id) => {
    return axios.delete(`http://localhost:4000/api/tasks/${id}`)
  }, {
    onSuccess: () => {
      queryClient.invalidateQueries('tasks')
    }
  })
  const createTaskMutation = useMutation((task: Partial<Task>) => {
    return axios.post(`http://localhost:4000/api/tasks`, task)
  }, {
    onSuccess: () => {
      queryClient.invalidateQueries('tasks')
    }
  })
  const updateTaskMutation = useMutation(({id, user, ...task}: Partial<Task>) => {
    return axios.put(`http://localhost:4000/api/tasks/${id}`, task)
  }, {
    onSuccess: () => {
      queryClient.invalidateQueries('tasks')
    }
  })

  const closeModal = () => {
    modalState = {
      show: false,
      task: null,
    }
  }

  const saveTask = (task: Task) => {
    if (task.id) {
      $updateTaskMutation.mutate(task)
    } else {
      $createTaskMutation.mutate(task)
    }
    closeModal()
  }

  $: filteredTasks = filterTasks($queryResult?.data?.data, currentTab)
</script>

{#if $queryResult.isLoading}
    <span>Loading...</span>
{:else if $queryResult.error}
    <span>An error has occurred: {$queryResult.error.message}</span>
{:else}
    <ul class="nav nav-tabs">
        {#each Object.values(taskTabs) as tab}
            <a class="nav-link" class:active={tab === currentTab} href="#"
            on:click={() => currentTab = tab}>{tab}</a>
        {/each}
    </ul>
    {#each filteredTasks as task}
        <TaskCard {task}
                  on:deleteTask={({detail}) => $deleteTaskMutation.mutate(detail)}
                  on:onClick={(detail) => modalState = {show: true, task: detail}}
        />
    {/each}
{/if}
<br/>
<br/>
<br/>
<button on:click={() => modalState.show = true}>Create task</button>
<MutateTaskModal
        on:close={closeModal}
        on:save={(e) => saveTask(e.detail)}
        show={modalState.show}
        task={modalState.task}
/>

// fullstack/next-app/pages/tasks.tsx
import { prisma } from "../prisma";
import { Task } from "../models";
import Layout from "../components/layout";
import { TaskCard } from "../components/taskCard";
import { useEffect, useState } from "react";
import { MutateTaskModal } from "../components/mutateTaskModal";

const taskTabs = {
  all: 'All',
  upcoming: 'Upcoming',
  done: 'Done'
}

export default function Tasks({ tasks: _tasks }: { tasks: Task[] }) {
  const [currentTab, setCurrentTab] = useState(taskTabs.all)
  const [tasks, setTasks] = useState<Task[]>(_tasks)
  const [filteredTasks, setFilteredTasks] = useState<Task[]>([])
  const [modalProps, setModalProps] = useState<{ show: boolean, task: Task | null }>({ show: false, task: null })

  const updateTask = async (id: number, task: Partial<Task>) => {
    const res = await fetch(`/api/task/${id}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(task),
    })
    const data = await res.json()
    setTasks(tasks.map(x => {
      if (x.id === id) return { ...x, ...data }
      else return x
    }))
  }

  const deleteTask = async (id: number) => {
    await fetch(`/api/task/${id}`, {
      method: 'DELETE',
    })
    setTasks(tasks.filter(x => x.id !== id))
  }

  const createTask = async (newTask: Partial<Task>) => {
    const res = await fetch(`/api/tasks`, {
      method: 'POST',
      body: JSON.stringify(newTask)
    })
    const { task } = await res.json()

    setTasks([task, ...tasks])
    setModalProps({ show: false, task: null })
  }

  const filterTasks = (tasks: Task[]) => {
    switch (currentTab) {
      case taskTabs.all:
        setFilteredTasks(tasks)
        break
      case taskTabs.upcoming:
        setFilteredTasks(tasks.filter(x => x.time && new Date() < new Date(x.time)))
        break
      case taskTabs.done:
        setFilteredTasks(tasks.filter(x => x.status === 'done'))
        break
    }
  }

  useEffect(() => {
    filterTasks(tasks)
  }, [currentTab, tasks])

  return (
    <Layout>
      <article className="panel is-primary">
        <p className="panel-tabs" style={{ position: 'relative' }}>
          {Object.values(taskTabs).map((v, i) => (
            <a
              key={i}
              className={v === currentTab ? 'is-active' : ''}
              onClick={() => setCurrentTab(v)}
            >{v}</a>
          ))}
          <button
            className="button is-success is-small"
            style={{ position: 'absolute', right: '2px', alignSelf: 'center' }}
            onClick={() => setModalProps({ show: true, task: null })}
          >Add task</button>
        </p>
        {filteredTasks.map((task, i) => (
          <TaskCard
            task={task}
            key={i}
            updateTask={updateTask}
            deleteTask={deleteTask}
            onClick={(event) => setModalProps({ show: true, task: event })}
          />
        ))}
      </article>
      <MutateTaskModal
        isActive={modalProps.show}
        taskToUpdate={modalProps.task}
        createTask={createTask}
        updateTask={(id, task) => {
          updateTask(id, task);
          setModalProps({ show: false, task: null })
        }}
        close={() => setModalProps({ show: false, task: null })}
      />
    </Layout>
  )
}

export async function getServerSideProps() {
  const tasks = (await prisma.$queryRaw`
    SELECT "task".*, json_build_object('id', "user"."id", 'image_url' ,"user"."image_url") as "user" FROM "tasks" as "task" 
    LEFT JOIN "users" as "user" on "user"."id" = "task"."user_id"
    WHERE "task"."status" != 'deleted'
    GROUP BY "task"."id", "user"."id"`)

  return {
    props: {
      tasks: JSON.parse(JSON.stringify(tasks))
    }
  }
}
