// fullstack/next-app/components/navbar.tsx
import Link from "next/link";
import {useRouter} from "next/router";

export default function Navbar() {
  const router = useRouter()

  return (
    <nav className="navbar is-light" role="navigation" aria-label="main navigation">
      <div className="navbar-menu">
        <div className="navbar-start">
          <Link href="/tasks">
            <a className={`navbar-item ${router.pathname === '/tasks' && 'is-active'}`}>
              Tasks
            </a>
          </Link>

          <Link href="/people">
            <a className={`navbar-item ${router.pathname === '/people' && 'is-active'}`}>
              People
            </a>
          </Link>
        </div>
      </div>
    </nav>
)
}

// frontend/svelte-app/src/lib/Navbar.svelte
<script lang="ts">
  let expandNavbar = false;
</script>

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">TODO app</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
      on:click={() => (expandNavbar = !expandNavbar)}
    >
      <span class="navbar-toggler-icon" />
    </button>
    <div
      class="collapse navbar-collapse"
      class:show={expandNavbar}
      id="navbarSupportedContent"
    >
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/tasks">Tasks</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users">Users</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
